### ISSUE TITLE
Front-facing wrapper function for r_main_parallel

### ISSUE THREAD

**Issue by sscogges** [Scott-Coggeshall/bigrq#1]
We want to create a front-facing wrapper function that the user will interact with. This function should do basic error checking, assign any needed intermediate variables based off the inputs, call `r_main_parallel` to fit the model, then process and return the results plus meta-data.

**Comment by sscogges** [comment]
# Input Arguments

The wrapper function should take the following input arguments

- [ ] `x` a matrix (or object coercible to a matrix) containing the design matrix for the quantile regression
- [ ] `y` a vector (or object coercible to a vector) containing the values of the outcome variable
- [ ] `M` an integer, the number of blocks to split the data into when fitting the model. Default is 1.
- [ ] `intercept` a logical value indicating whether an intercept should be included in the model. Default is TRUE.
- [ ] `max_iter` an integer, the maximum number of iterations that the algorithm should run for. Default is 500.
- [ ] `min_iter` an integer, the minimum number of iterations that the algorithm should run for. Default is 10.
- [ ] `n_workers` an integer, the number of worker processes that should be created. Default is `floor(parallel::detectCores()/2)` i.e. (about) half of the available cores/processors.
- [ ] `lambda` a numeric or numeric vector specifying the value(s) of the tuning parameter lambda. Default is 1.
- [ ] `tau` a numeric value between 0 and 1 specifying the conditional quantile to estimate. Default is 0.5.
- [ ] `rho` a positive numeric value used in fitting the QRADMM algorithm.
- [ ] `alpha` a positive numeric value used in fitting the QRADMM algorithm.
- [ ] `penalty` a string specifying the type of penalty that should be applied to the model parameters. Current options are `lasso`, `scad` and `mcap`. Default is `lasso`.
- [ ] `inverses_read_path` a character string giving a file path to a .rds object that contains a list of cached inverses. Default is NULL.
- [ ] `inverses_write_path` a character string giving a file path. If supplied, the inverses calculated during the model fitting process will be saved as an .rds object to the specified location. Default is NULL.
- [ ] `abstol` a positive numeric value for determining convergence.
- [ ] `reltol` a positive numeric value for determining convergence.

**Comment by sscogges** [comment]
# Error Checking

The wrapper function should perform the following checks at the beginning of the function:

- [ ] Confirm that `x` is a numeric matrix or can be converted to a numeric matrix. If not, return an error.
- [ ] Confirm that `y` is a numeric vector or can be converted to a numeric vector. If not, return an error.
- [ ] Confirm that the number of rows of `x` matches the number of observations in `y`. If not, return an error.
- [ ] Confirm that `M` is numeric or integer. If not, return an error.
- [ ] Confirm that `intercept` is a logical value or can be converted to one. If not, return an error.
- [ ] Confirm that `max_iter` is numeric or integer. If not, return an error.
- [ ] Confirm that `min_iter` is numeric or integer. If not, return an error.
- [ ] Confirm that `n_workers` is numeric or integer. If not, return an error.
- [ ] Confirm that `n_workers` is less than or equal to the number of available cores/processors as returned by `parallel::detectCores()`. If not, return an error.
- [ ] Confirm that `lambda` is a numeric scalar or numeric vector. If not, return an error.
- [ ] Confirm that `tau` is between 0 and 1. If not, return an error.
- [ ] Confirm that `rho` is a positive scalar. If not, return an error.
- [ ] Confirm that `alpha` is a positive scalar. If not, return an error.
- [ ] Confirm that `penalty` is one of either `lasso`, `scad` or `mcap`. If not, return an error.
- [ ] Confirm that `abstol` is a positive scalar. If not, return an error.
- [ ] Confirm that `reltol` is a positive scalar. If not, return an error.

The R function `try` is useful for attempting operations that may fail. The function `stop` is useful for creating custom error messages.

**Comment by sscogges** [comment]
# Intermediate Variables and Actions

Before calling `r_main_parallel`, the wrapper function should create the following variables and perform the following actions based on the function inputs:

- [ ] Check that `M`, `intercept`, `max_iter`, `min_iter`, `n_workers`, `tau`, `rho`, `alpha`, `penalty`, `abstol` and `reltol` are all scalars i.e. of length 1. For each of these inputs with length greater than 1, take the first element and assign it to that variable e.g. `M <- M[1]`. Then output a warning along the lines of "X has length greater than 1, only using first element and ignoring the rest".

- [ ] If `x` is a non-matrix object that can be converted to a matrix (e.g. a data frame), perform that conversion.

- [ ] If `intercept = TRUE`, add a vector of 1s as the first column of `x` and name that column "Intercept".

- [ ] Column-bind the outcome `y` and the matrix `x` into one matrix, with `y` as the first column.

**Comment by sscogges** [comment]
# Function Output

**Comment by Scott-Coggeshall** [comment]
tracking this stuff in Notion now
